# CRD example - create Source Provider for Anthos clusters on AWS
# [START source]
apiVersion: anthos-migrate.cloud.google.com/v1beta2
kind: SourceProvider
metadata:
  name: migration-source-name
spec:
  localAws:
    # Google Cloud region of cluster.
    region: my-region
    accessKeyId: admin
    secretAccessKey:
      secretRef:
        name: secret-aws
        namespace: v2k-system
# [END source]