# CRD example - create Source Provider for compute engine
# [START source]
apiVersion: anthos-migrate.cloud.google.com/v1beta2
kind: SourceProvider
metadata:
  name: migration-source-name
spec:
  gce:
    project: my-project
    serviceAccount:
      secretRef:
        name: my-secret
        namespace: v2k-system
# [END source]