# CRD example - create linux migration CRD
# [START create_linux_migration]
apiVersion: anthos-migrate.cloud.google.com/v1
kind: Migration
metadata:
  name: my-migration
  namespace: v2k-system
spec:
  type: linux-system-container
  sourceSnapshotTemplate:
    spec:
      sourceProviderRef:
        name: my-ce-src
      sourceId: my-id
# [END create_linux_migration]