# CRD example - create Source Provider for anthos on local vmware
# This used also for BareMetal
# [START source]
apiVersion: anthos-migrate.cloud.google.com/v1beta2
kind: SourceProvider
metadata:
  name: migration-source-name
spec:
  localVmware:
    address: 1.2.3.4
    username: admin
    password:
      # Password for your vcenter.
      secretRef:
        name: secret-vcenter
        namespace: v2k-system
# [END source]